import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { UPLOAD_LIMITS } from "@naruto-ccg/shared";

/**
 * Storage abstraction. Business logic only ever deals with opaque string "keys"
 * (e.g. "collections/<userId>/<uuid>.jpg"). Swap LocalStorage for S3 / R2 / Cloudinary
 * by implementing StorageDriver and returning it from getStorage().
 */
export interface StorageDriver {
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<{ data: Buffer; contentType: string } | null>;
  delete(key: string): Promise<void>;
}

const CONTENT_TYPES: Record<string, string> = {
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
  svg: "image/svg+xml", // only ever produced by the trusted seed script
};

const KEY_RE = /^[a-z0-9][a-z0-9/_-]*\.[a-z0-9]{2,5}$/i;

/** Keys are generated by us; still validate before touching the filesystem. */
export function isSafeKey(key: string): boolean {
  return KEY_RE.test(key) && !key.includes("..") && !key.includes("//");
}

function findRepoRoot(start = process.cwd()): string {
  let dir = start;
  for (;;) {
    if (existsSync(path.join(dir, "pnpm-workspace.yaml"))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return start;
    dir = parent;
  }
}

export function resolveUploadDir(): string {
  const configured = process.env.UPLOAD_DIR || "./uploads";
  return path.isAbsolute(configured) ? configured : path.resolve(findRepoRoot(), configured);
}

export class LocalStorage implements StorageDriver {
  constructor(private readonly root: string = resolveUploadDir()) {}

  private resolve(key: string): string {
    if (!isSafeKey(key)) throw new Error("Invalid storage key");
    const full = path.resolve(this.root, key);
    if (!full.startsWith(path.resolve(this.root) + path.sep)) throw new Error("Invalid storage key");
    return full;
  }

  async put(key: string, data: Buffer): Promise<void> {
    const file = this.resolve(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, data);
  }

  async get(key: string) {
    if (!isSafeKey(key)) return null;
    try {
      const data = await readFile(this.resolve(key));
      const ext = key.split(".").pop()!.toLowerCase();
      const contentType = CONTENT_TYPES[ext];
      if (!contentType) return null;
      return { data, contentType };
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    if (!isSafeKey(key)) return;
    await rm(this.resolve(key), { force: true });
  }
}

let storage: StorageDriver | undefined;
export function getStorage(): StorageDriver {
  if (!storage) {
    switch (process.env.STORAGE_DRIVER ?? "local") {
      case "local":
        storage = new LocalStorage();
        break;
      default:
        throw new Error(`Unsupported STORAGE_DRIVER "${process.env.STORAGE_DRIVER}"`);
    }
  }
  return storage;
}

/** Public URL for a stored key, relative to the app that serves /uploads (admin uses a basePath). */
export function storageUrl(key: string | null | undefined, prefix = "/uploads"): string | null {
  if (!key) return null;
  if (/^https?:\/\//i.test(key)) return key; // remote image URL (e.g. from import)
  return `${prefix}/${key}`;
}

// ---------- image validation ----------

export class UploadError extends Error {}

function sniff(buf: Buffer): "jpg" | "png" | "webp" | null {
  if (buf.length > 12 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return "jpg";
  if (buf.length > 8 && buf.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return "png";
  if (buf.length > 12 && buf.subarray(0, 4).toString("ascii") === "RIFF" && buf.subarray(8, 12).toString("ascii") === "WEBP") return "webp";
  return null;
}

export interface ValidatedImage {
  data: Buffer;
  ext: "jpg" | "png" | "webp";
  contentType: string;
}

/** Checks declared MIME, extension, size and real file signature. The original filename is never reused. */
export async function validateImage(file: File): Promise<ValidatedImage> {
  if (file.size === 0) throw new UploadError("File kosong.");
  if (file.size > UPLOAD_LIMITS.maxBytes) throw new UploadError(`Ukuran file terlalu besar (maks ${UPLOAD_LIMITS.maxBytes / 1024 / 1024} MB).`);

  const allowedExts = UPLOAD_LIMITS.allowed[file.type];
  if (!allowedExts) throw new UploadError("Hanya gambar JPEG, PNG, dan WebP yang diizinkan.");

  const nameExt = file.name.split(".").pop()?.toLowerCase() ?? "";
  if (!allowedExts.includes(nameExt)) throw new UploadError("Ekstensi file tidak sesuai dengan tipe gambar.");

  const data = Buffer.from(await file.arrayBuffer());
  if (data.length > UPLOAD_LIMITS.maxBytes) throw new UploadError("Ukuran file terlalu besar.");
  const real = sniff(data);
  if (!real || !allowedExts.includes(real)) throw new UploadError("Isi file bukan gambar yang valid sesuai tipe yang dinyatakan.");

  return { data, ext: real, contentType: file.type };
}

/** Validate + store an image under `folder`, returning the storage key. */
export async function saveImage(folder: string, file: File): Promise<string> {
  if (!/^[a-z0-9][a-z0-9/_-]*$/i.test(folder) || folder.includes("..")) throw new Error("Invalid folder");
  const img = await validateImage(file);
  const key = `${folder}/${randomUUID()}.${img.ext}`;
  await getStorage().put(key, img.data, img.contentType);
  return key;
}

/**
 * Shared handler for GET /uploads/[...path] in both apps.
 * `authorize` lets the app gate private keys (e.g. collection photos) before any bytes are read.
 */
export async function serveUpload(segments: string[], authorize?: (key: string) => boolean | Promise<boolean>): Promise<Response> {
  const key = segments.join("/");
  if (!isSafeKey(key)) return new Response("Tidak ditemukan", { status: 404 });
  // 404 (not 403) so the existence of private files is not revealed.
  if (authorize && !(await authorize(key))) return new Response("Tidak ditemukan", { status: 404 });
  const found = await getStorage().get(key);
  if (!found) return new Response("Tidak ditemukan", { status: 404 });
  const isPrivate = key.startsWith("collections/") || key.startsWith("avatars/");
  return new Response(new Uint8Array(found.data), {
    headers: {
      "Content-Type": found.contentType,
      "Cache-Control": isPrivate ? "private, max-age=300" : "public, max-age=3600",
      "X-Content-Type-Options": "nosniff",
      "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; sandbox",
    },
  });
}
